### ISSUE TITLE
 Создать пустой проект ENIMI

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#1]
### Конечный результат:
Создать пустой проект ENIMI и настроить директории STATIC, UPLOADS. Файл .gitignore

### План решения:
 Создать приложение Accounts. Подключить в settings. 
   Создать: пакет models, папку templates, пакет views
   Создать файлы: urls, forms, managers

настроить файл .gitignore
добавить туда же venv, __pycache__, .idea, *.sqlite3
### Мотивация:
 Чтоб начать уже создание нового нашего проекта ENIMI
### Планируемое время работы: 
1 час

**Comment by TanitaDev** [comment]
### Создание пустого проекта

Создала пустой проект на Django 3.2
Добавила необходимые по задаче пакеты, папки и файлы
Произвела настройку для файлов

**Comment by TanitaDev** [comment]
### Создание пустого проекта
Создала пустой проект на Django 3.2
Добавила необходимые по задаче пакеты, папки и файлы
Произвела настройку для файлов

**Comment by TanitaDev** [comment]
### Создание пустого проекта
#### Ожидаемое время: 1 час

Создала пустой проект на Django 4.1.4

#### Добавила необходимые по задаче пакеты, папки и файлы:
- создала файл зависимостей requirements.txt
- создала приложение accounts
- создала папку для шаблонов templates в корне проекта и в проекте accounts
- создала файл для стилей style.css в папке static/css
- создала тестовый view и url для проверки открытия главной страницы
- добавила папки view, models, urls


#### Произвела настройку для файлов:
- подключила static и media в settings.py
- изменила язык с английского на русский в settings.py

#### Согласовала структуру пустого проекта с капитаном и аналитиком:

#### Затраченное время: 3 часа
