### ISSUE TITLE
Создание мокапов страниц регистрации, личных кабинетов

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#16]
## Конечный результат:
Результаты данной задачи благодаря визуализации улучшат понимание Заказчиком того как будет работать регистрация, как будет выглядеть личный кабинет на который он будет перенаправлен после регистрации и какой функционал его там ожидает:

Созданы мокапы страниц регистрации:
- репетитора
- родителя
- ученика
- учебного центра

Созданы мокапы личных страниц:
- репетитора
- родителя с привязкой к ученику 
- родителя без привязки к ученику 
- ученика если он самостоятельно зарегистрирован и не привязан к родителю
- ученика привязанного к родителю
- учебного центра

## План решения:
Необходимо создать мокапы страниц регистрации, личных кабинетов (5 видов с учетом родитель/ученик со своей спецификой). В личном кабинете отразить местоположение модулей, кнопок для редактирования.

_На примере родителя._
- Раздел дети (простой список на каком-нибудь участке страницы), отражающий список детей, нажав на которого можно провалиться на страницу с его успеваемостью.
- Личная информация пользователя.
- Кнопка добавить ребенка.
- Кнопка редактировать личные данные.
- Кнопка изменить пароль.
- Кнопка привязать карту.
- И т.д.

## Мотивация:
После согласования мокапов Заказчиком, будет обеспечена некоторая гарантия того, что разработчик будет двигаться в правильном направлении при написании кода, а также минимизирует риск того, что конечный результат не понравится Заказчику, позволит избежать впустое потраченное время на написание кода.
Один из важных факторов - облегчить первичную регистрацию пользователя с минимальным набором полей.
После чего пользователь попадает в красивый, приятный личный кабинет (атмосфера комфорта) и может заполнить оставшиеся данные когда угодно.

## Критерии приемки:
Критерием приемки является грамотно оформленные мокапы. Желательно на специализированном инструменте, способным показать страницы в виде презентации.

**Comment by asmossunov** [comment]
Созданы мокапы для пользователей трех типов:
Студент, Репетитор,  Родитель студента(ребенка)

**Comment by asmossunov** [comment]
Запланированное время: 4 дня
Затратил: 7 дней

**Comment by asmossunov** [comment]
Запланированное время: 4 дня
Затратил: 7 дней
