### ISSUE TITLE
Поиск инструмента для создания мокапов

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#17]
Приветствуется простой и удобный в использовании инструмент (в крайнем случае можно использовать инструменты MS Office).
Описать как достать инструмент, какие шаги предпринять для начала работы, какими возможностями обладает.

**Comment by nurilaassyk** [comment]
### Конечный результат:
Есть простой и удобный инструмент для рисования мокапов по проекту

 ### План решения:

Изучить доступные инструменты для рисования мокапов и выбрать наиболее подходящее. Написать краткую инструкцию по использованию

### Мотивация:
Нужна для рисования мокапов и согласования с заказчиком для продуктивной работы над проектом

### Критерии приемки:
Ссылка на программу по рисованию мокапов
Краткая инструкция по использованию

### Планируемое время выполнения:  3 часа 

### Реальное время выполнения:  5 часов

**Comment by asmossunov** [comment]
Потребовалось затратить времени больше запланированного.
Поиск показал, что существует огромное количество программ для создания мокапов. Все они со своими плюсами и минусами. Поиск привел меня к программе Adobe XD, которая позволяет не только создавать мокапы но и конструировать прототипы сайтов. Был проведен анализ её функционала. Вся дальнейшая работа во время итерации была связана с разработкой мокапов и прототипов страниц приложения.
 
Затраченное на поиск время и пробный мокап заняли 5 часов.

**Comment by Rashid-ad-din** [comment]
Мокапы, созданные в данном приложении просмотрены. Приложение имеет широкий функционал. Принято.
