### ISSUE TITLE
Логика регистрации и прикрепления ребенка к родителю

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#18]
Описать логики регистрации и прикрепления ребенка к родителю (какое поле будет уникальным и т.д.)

Планируемое время выполнения: 7 часов

**Comment by Alnazhm** [comment]
Реализована связь, привязка родителя ребенку есть и регистрация ребенка с аккаунтом и без аккаунта работает

**Comment by nurilaassyk** [comment]
### Конечный результат:
Реализовать понятную и рабочую связь между пользователем родитель и пользователем ребенок.

### План решения:
- Создать модели родителя и ребенка
- Создать таблицу в базе данных для сущности родитель
- Создать таблицу в базе данных для сущности ребенок
- Осуществить связь между двумя сущностями

### Мотивация:
Для понимания и дальнейшей реализации проекта нужно реализовать связь между этими сущностями.

### Критерии приемки:

- Реализована связь, привязка родителя ребенку 
- Есть и регистрация ребенка с аккаунтом и без аккаунта 


### Планируемое время выполнения:

### Реальное время выполнения

**Comment by Rashid-ad-din** [comment]
Функционал протестирован. Ученик успешно создается как отдельный самостоятельно управляемый аккаунт и как управляемый родителем аккаунт.

**Comment by Alnazhm** [comment]
Реальное потраченное время на выполнения: 10 часов потрачено
