### ISSUE TITLE
Редактирование wikies

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#19]
- Раздел "Gitflo". Вопросы удалить. Отредактировать надлежащим образом, обозначить правила.
Одно из правил - именовать ветки по функционалу.
- В отчете о встрече с заказчиком удалить жирный шрифт для вопросов, чтобы в блоке справа не отражалось много лишней информации.
(Сам раздел pages не удален, посему считаю целесообразным поддерживать грамотное оформление)
- Вместо ссылок указать текстом в теле страницы в разделе "Правила составления тикетов".
- Cоздать отдельные ссылки и страницы по описанию каждого типа задач.
- Добавить в projects статус "test". Промежуточный этап между "in progress" и "done".

**Comment by nurilaassyk** [comment]
### Конечный результат:

Понятный и аккуратный вид документации, разделенный по логическим блокам для удобства поиска и применения пользователями.

### План решения:

- Создать раздел ",библиотека" где будут хранится документация к технологиям, которые команда принимает
- Создать раздел "инструкции" где будут хранится все правила работы команды
- Создать раздел "отчеты" для хранения отчетов команды

### Мотивация

Нужна для структурирования файлов, документов и инструкция и удобного поиска

### Критерии приемки:

В меню навигации вики есть разделы:

- Документация
- Правила
- Отчеты

### Планируемое время выполнения
3 часа

### Реальное время выполнения
3 часа
