### ISSUE TITLE
Верстка - дизайн главной страницы

### ISSUE THREAD

**Issue by nurilaassyk** [ladukwek/ESDP-AP7-ATTRACTOR#20]
### Конечный результат:
Реализовать верстку - дизайн главной страницы с учетом требований от заказчика

### Мотивация:
Улучшив внешний вид главной страницы, мы поможем пользователям легко ориентироваться в системе. 

### План решения:
- реализовать навбар в соответствии с мокапом заказчика
- если пользователь в системе, убрать кнопки вход
- если не в системе убрать выход
- добавить кнопки репетиторы, как это работает, главная
- вставить картинку фоном под навбаром
- Предупреждающие знаки по типу "!" и уведомлений сделать красными #E85A4F
- Все цвета должны быть градиентными или глянцевыми. Преимущественный цвет #5680E9, дополнительные все остальные
- Цветовая гамма:
![image](https://user-images.githubusercontent.com/113448331/208888615-92c12502-0e25-4b08-9fde-1df7051c7c3b.png)

### Критерии приёмки:
При загрузке главной страницы на экране пользователь должен видеть навбар с кнопками как в мокапе заказчика, главную картинку.

**Comment by TanitaDev** [comment]
#### Планируемое время - 2 часа

### Навбар
- реализовала навбар под требования заказчика:
  добавила в меню: Главная, Как это работает, Стать репетитором, Больше
- наполнила контент навбара по мокапу
- изменила цвета текста навбара под цветовую гамму от заказчика

### Основная страница
- изменила текст контента под мокап заказчика:
 добавила блоки: Популярные предметы, Репетиторы, Новое в блоге, Отзывы о репетиторах
- изменила цветовую гамму под требования заказчика
- удалила блоки не подходящие к тематике проекта

##### Цвета кнопок сделаны градиентными, основной цвет - #5680E9

Верстка загруженна на отдельную ветку - enimi-templates-edustage

#### Затраченное время - 6 часов
