### ISSUE TITLE
Поиск готового дизайна

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#22]
Необходимо найти готовый дизайн для внедрения в проект и минимизировать время, затраченное на написание кода в части front-end.
Дизайн должен отображать необходимую информацию на страницах в соответствии с требованиями Заказчика. Дизайн должен иметь приятный стиль.

**Comment by TanitaDev** [comment]
#### Планируемое время: 2 часа
### Поиск шаблонов
Нашла два варианта готового дизайна с сайта [www.freehtmlthemes.ru](http://www.freehtmlthemes.ru/) :
"academics" и "edustage".
Шаблоны согласованны с капитаном.

#### Принято решение выбрать шаблон "edustage" так как он:
Отображает более подходящую информацию на страницах, в соответствии с требованиями Заказчика.
Имеет удобную структуру папок и файлов.
Имеет готовый адаптив страниц.
Более приятен по дизайну.
Более подходит тематике проекта.
Выбранный шаблон - "edustage", согласован со всей командой

#### Затраченное время: 4 часа

**Comment by TanitaDev** [comment]
#### Планируемое время: 2 часа
### Поиск шаблонов
Нашла два варианта готового дизайна с сайта [www.freehtmlthemes.ru](http://www.freehtmlthemes.ru/) :
"academics" и "edustage".

Структура шаблона показана капитану, проанализирована и согласованна. 

#### Принято решение выбрать шаблон "edustage", так как он:
- отображает более подходящую информацию на страницах, в соответствии с требованиями Заказчика.
- имеет удобную структуру папок и файлов.
- имеет готовый адаптив страниц.
- более приятен по дизайну.
- более подходит тематике проекта.

Выбранный шаблон - "edustage", согласован с командой и ментором.

#### Затраченное время: 4 часа

**Comment by Rashid-ad-din** [comment]
Решение задачи соответствует требованиям. Принято.
