### ISSUE TITLE
Личный кабинет репетитора

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#26]
### Конечный результат:
Реализация личного кабинета репетитора со всем функционалом, который необходим заказчику

### Мотивация:
Личный кабинет репетитора необходим для просмотра профиля репетитора, где отображенны все его необходимые данные.
Кроме того, личный кабинет необходим для редактирования информации о себе, своих курсах и своем расписании.

### Верстка:
**_верстка осуществляется по мокапу предоставленному Антоном (@asmossunov )_**

#### **верстка формы создания анкеты:**
- при нажатии на кнопку "создать анкету" всплывает модальное окно с формой для заполнения **анкеты**:
- сверстать саму форму Анкеты
- там где выбрать можно несколько вариантов - используется checkbox, там где выбрать можно только один вариант - используется radio button

### **Мокапы**
![Профиль_репетитора_главная_вторая_версия](https://user-images.githubusercontent.com/113420698/210772980-c3ce8bb3-2879-4f5a-bf65-4c8fd7fa0941.png)
![Репетитор-Анкета](https://user-images.githubusercontent.com/113420698/210772999-591c049c-a20e-40bc-9402-4c4f7afe5529.png)
![Репетитор - Анкета](https://user-images.githubusercontent.com/113420698/210773031-188038b4-95fc-40a1-ad8c-d6a75656ad07.png)

#### **верстка табов для переключения между разделами:**
- для решения задачи по табам можно взять:
1. jquery UI
2. код пользователей из источников в гугле, например: сайт W3Schools
3. написать код самому используя JS
![Репетитор - Анкета](https://user-images.githubusercontent.com/113420698/210773031-188038b4-95fc-40a1-ad8c-d6a75656ad07.png)

### Бэкенд:
- создать, если необходимо, классовую форму для анкенты
- создать, если необходимо, view для личного кабинета, заполнения анкеты, редактирования анкеты, редактирования профиля и пр.

- прописать urls
- поля заполнения анкеты: 
  1. дата рождения, пол, язык преподавания, описание себя (**все поля обязательные**)
  2. **Информация в Вашем образовании**: Имя ВУЗа, специальность, степень(graduate), документы, checkbox образование закончено или нет
  3.  **Дисциплина и стоймость занятий**: имя дисциплины, цена, опыт
  4. **Форма занятий**: онлайн, на дому, своё место (checkbox)
  
    #### **все поля заполнения анкеты обязательны**

- перенаправления:
  после редактирования профиля и заполнения анкеты пользователь остается в своем личном кабинете

### Критерии приёма:
- При переходе в личный кабинет репетитора, пользователь(репетитор) видит свой профиль, где есть фото, личные данные, расписание, редактирование личных данных и заполнение своей анкеты и свою заполненую анкету.
- В личном кабинете репетитора при нажатии на кнопку "создать анкету" должно всплывать модальное окно с формами создания анкеты
- Переключение по табам должно происходить без перезагрузки страницы
- При незаполнении обязательных полей должна быть валидация

**Comment by Rashid-ad-din** [comment]
Планируемое время - 16 часов.
Затраченное время - 44 часа.

Сложность заключалась в сложной структуре БД со множественными связями один-к-одному, один-ко-многим.
Соответственно, возникла сложность с обработкой данных во вьюшках. Особая сложность возникла с блоком Формат обучения.
Также, сложность возникла при реализации дополнительного функционала по смене пароля без выхода из сессии.
Немало времени потрачено на работу с фронтендом.
