### ISSUE TITLE
Подключение главной страницы к основному проекту на Django

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#28]
### Конечный результат:
Подключение основной страницы к Django со всеми стилями и скриптами.

### Мотивация:
Главная страница необходима для просмотра репетиторов, курсов и учеников. Также гл. страница необходима для показа необходимой информации о сайте.

### План решения:
- определить индексную страницу в необходимую папку
- поместить стили и скрипты в правильные папки
- прописать пути в urls для открытия главной страницы
- проверить работу стилей и скриптов на главной странице

### Критерии приёма:
- при запуске проекта на Django должна открываться главная страница 
- стили и скрипты должны работать также как на шаблоне верстки без бэкенда
- названия и структура папок и файлов должны соотвествовать правилам прописанным по этой [ссылке](https://github.com/ladukwek/ESDP-AP7-ATTRACTOR/wiki/%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8)

**Comment by asmossunov** [comment]
Страница подключена. Функционал навигационной панели в охвате текущих задач реализован.
