### ISSUE TITLE
Потдверждение email при регистарции

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#29]
## Конечный результат:
* Реализовать подтверждение email при регистрации пользователя

## План решения:
* Написать MVC для функционала
При заполнении всех полей (и поля email в том числе) сервер отправляет на этот адрес письмо для подтверждения email. В нём содержится ссылка. После перехода по этой ссылке пользователь возвращается на страницу регистрации где успешно регистрируется. Необходимо описать представления для реализации этого функционала. 

## Мотивация:
* Нужна для того, чтобы система могла идентифицировать пользователя и его email.

## Критерии приемки:
* Перейти на страницу регистрации
* Откроется страница регистрации
* Заполнить все поля и нажать кнопку "Зарегистрироваться"
* На почту должно прийти письмо для подтверждения регистрации
* После перехода по ссылке из письма регистрируемся и попадаем в страницу входа
* Авторизоваться и убедиться, что все работает

## Планируемое время выполнения:
* 5 часов

**Comment by nurilaassyk** [comment]
Работа выполнено за 6 часов
