### ISSUE TITLE
 Создать модель Account. Регистрация типа пользователя 'student'

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#3]
### Мотивация
Для того , чтобы пользователь мог произвести регистрацию как ученик и он отличался по своим правам и возможностям от других типов пользователей его необходимо зарегистрировать с типом "student"

### План решения:
 От абстрактного пользователя создать модель Account исключив поле username
Также необходимо описать доп. поля:
 type - тип пользователя, father_name - отчество, email - почт. ящик, phone - телефон, avatar - аватар, is_deleted, created_at, updated_at 
 
 отчество не обязательно заполнять в форме - blank=True. 
 аватар - blank=True. Дефолтное значение аватара в папке uploads:
 default='default_avatar/default-user.png'  
 Остальные поля - обязательны к заполнению. 

 Настроить авторизацию по email используя UserManager():
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()
    
 В файле managers.py создать класс UserManager(BaseManager):
        
 Создать представление AccountCreateView.  
     
 В файле forms.py создать форму для регистрации пользователя. Он же ученик.
      
Создать шаблон для формы регистрации пользователя.

   
### Критерии приёмки:
На главной странице нажимаем кнопку регистрация.
Выпадает список, в котором выбираем тип пользователя для регистрации
При выборе типа "ученик"  загружается форма для регистрации пользователя. После нажатия кнопки "зарегистрироваться" создаётся пользователь с типом student и происходит авторизация. В таблице accounts создается новая запись с типом пользователя student
  
### Планируемое время работы:  
3 часа

**Comment by Rashid-ad-din** [comment]
Задача выполнена.
_Затраченное время - 5 часов._
Во время выполнения возникла проблема - после создания миграций (до создания модели Accounts), была создана таблица auth_user и superuser создавался именно в нее, а не в таблицу accounts_acccount. В settings было прописано AUTH_USER_MODEL = 'accounts.Account'.
Из-за структуры проекта, возникла необходимость прописать в файле **accounts/models/__init__.py** следующий код - **from .accounts import Account**.
Django упорно не принимал новые миграции. Удаление базы и ручное удаление миграций не возымело эффекта.
_Проблема решена следующим образом:_
1. исполнением в терминале (ubuntu) следующих команд (ОС Widows 10, подсистема Linux):
 - find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
 - find . -path "*/migrations/*.pyc" -delete
2. После чего вручную удалена база данных.
3. Далее произведены миграции.
В результате таблица **auth_user** исчезла. И главной таблицей для пользователей является **accounts_account**.

Дополнительный функционал:
1. Изменена структура проекта. Папка templates с шаблонами base, index, navbar, а также вьюшка (IndexView) под названием base (переименована во views) перемещены из модуля accounts в ядро проекта (модуль enimi). После перемещения возникла проблема - Django не видел шаблон index. В settings прописано в разделе TEMPLATES **'DIRS': [BASE_DIR / 'enimi/templates']**;
2. В settings язык изменен на **'ru-ru'**;
3. Реализована вьюшка logout;
4. Удален лишний код в accounts/urls. Добавлен префикс auth в корневом файле urls;
5. В навбаре установлена проверка, если пользователь авторизован, отображаются его тип и ФИО. В модели Аккаунт реализован метод __str__ отображающий ФИО.

Примечание. При создании аккаунта поле **username** принимает такое же значение как **email**. Иначе не удается создать аккаунт, т.к. ругается на **UNIQUE CONSTRAINT FAILED**.
