### ISSUE TITLE
Изменить табы в личном кабинет навигацию

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#32]
### Конечный результат:
Разделы в личном кабинете должны переключаться с помощью кнопок навигации, а не по табам.

### Мотивация:
Навигация вводится для того, чтобы при сохранении редактирования пользователь оставался на то же странице что и был во время редактирования.

### План решения:
- создать панель навигации
- создать страницы для навигации
- перенести контен под навигацию

### Критерии приёма:
- вкладки в личном кабинете должны переключаться по навигации как отдельные страницы
- при редактировании по вкладкам навигации пользователь должен оставаться на той же странице что и реадактировал

**Comment by asmossunov** [comment]
В ходе реализации функционала и обсуждения с командой было принято решение в значительной степени отказаться от реализации без перезагрузки страницы. Был подобран вариант на основе Bootstrap шаблона панели навигации. 
Затраченное время  - 2 часа.
