### ISSUE TITLE
Cоздание страниц - доски объявлений репетитора и ученика с пагинацией

### ISSUE THREAD

**Issue by asmossunov** [ladukwek/ESDP-AP7-ATTRACTOR#40]
## Конечный результат:
* Реализовать страницу - список репетиторов и страницу - список учеников. 
Это доска объявлений с пагинацией. Каждая карточка содержит общее содержимое анкеты характерное для учеников и репетиторов
Также выводим в карточке фотографию репетитора или ученика, рейтинг, стоимость обучения. В дальнейшем реализуем 
функционал откликов на эти объявления. Более подробное описание полей есть в мокапе. При необходимости внесите дополнения и отразите здесь, в задаче. Также выделить место в шаблоне для окна поиска. Сам алгоритм поиска будет реализован позднее.  

## План решения:
* Написать urls для отображения этих страниц
* Написать представления 
* Сверстать страницы с карточками - объявлениями.
   Данные пользователей для карточек подтягиваются из БД. 
*  Карточки верстаем на основе мокапа  @asmossunov .
* В навигационной панели сделать ссылки для перехода на доски объявлений.
* Реализовать верстку для окна поиска по разным критериям. 
   Критерии описаны в мокапе. Место для окна поиска описано в мокапе
* Реализовать пагинацию   
   
![Список репетиторов](https://user-images.githubusercontent.com/113420698/210766210-9432fb39-2262-4ed8-8962-ad1d2dedc96d.png)

## Мотивация:
* Объявления нужны для того, чтобы пользователи могли находить друг друга для совместных занятий.
Репетитор ищет учеников, а ученики - репетиторов.

## Критерии приемки:
* Переходим по ссылке на страницу объявлений
* Откроется страница с карточками объявления
* В нижней части страницы находится пагинация

## Планируемое время выполнения:
* 15 часов

**Comment by Alnazhm** [comment]
Сделано
