### ISSUE TITLE
Реализация откликов пользователей

### ISSUE THREAD

**Issue by asmossunov** [ladukwek/ESDP-AP7-ATTRACTOR#41]
## Конечный результат:
* Реализовать функционал создания откликов пользователей: учеников на репетиторов и репетиторов на учеников.
 Откликнуться можно нажав кнопку "Связаться с пользователем(репетитором или учеником)" на карточке объявления на доске объявлений.

## План решения:
* Реализовать форму отклика при нажатии на кнопку  "Откликнуться" на объявлении
  В ней должно присутствовать приветственное сообщение и выбор предметов которые автор отклика желает 
  предложить. После нажатия на кнопку Создать отклик создаётся отклик в котором должны быть отражены следующие 
  поля: сообщение, автор отклика, анкета, на которую откликаются. 
* При открытии вкладки "Мои отклики" должна отобразиться карточка, на которой отражена информация об 
   анкете(пользователь) на которую я сделал отклик: Фото, имя, сообщение, инфо о предметах. На карточке должна 
 быть кнопка Чат, на нажатие которой впоследствии будет реализован функционал обмена сообщениями.
* Параллельно в кабинете владельца объявления во вкладке "Отклики на меня" должна отобразиться карточка с информацией о том кто откликнулся на наше объявление: фото, имя, предметы, сообщение. 
* Продумать систему взаимодействия пользователей и систему таблиц для реализации данного функционала
* Реализовать MVC
* Сверстать карточки
   Мокапы есть:
![Репетитор-отклики на меня](https://user-images.githubusercontent.com/113420698/210764683-3e4d1876-1b70-48c5-8a96-0760bba0ed76.png)
 

![Репетитор-Мои отклики](https://user-images.githubusercontent.com/113420698/210764836-4993c89e-8f89-4fc8-8766-7ed7ed4949c1.png)

## Мотивация:
* Функционал необходим для создания контакта между пользователями. Таким образом они смогут взаимодействовать друг с другом: составлять расписание занятий, оставлять сообщения.

## Критерии приемки:
* При нажатии кнопки "Откликнуться" на объявлении открывается форма отклика.
* Заполняем форму и нажимаем "Отправить отклик".
* Возвращаемся на страницу объявлений.
* В кабинетах пользователей появились соответствующие карточки с информацией об авторе отклика или пользователе-владельце объявления.
* При входе в личный кабинет в раздел откликов должна отображаться карточка с откликом и кнопкой для ведения чата.

## Планируемое время выполнения:
* 18 часов

**Comment by Alnazhm** [comment]
Сделано
