### ISSUE TITLE
Реализация чата между репетитором, самостоятельным учеником и родителем учеников

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#53]
**Конечный результат:**
Отображение чата между учителем/учеником.
Классический чат отображающий сообщения с правой стороны - автора, с левой - собеседника (желательно background  сообщений сделать в разных цветах, автор одного цвета, собеседник другого цвета).

**План решения:**
_Создать сущность Чат_
Необходимые поля:
* *Автор - внешний ключ к сущность Account.
* *Сообщение - 
* *Отклик - внешний ключ к сущности Отклик (Response).
* *Удалено - булево поле для отображения удалено ли сообщение или нет.
* *Дата создания - автоматическое проставление даты при добавлении записи. 

Создать вьюшки, шаблон, пути.

**Мотивация:**
Чат необходим для онлайн переписки учителя/ученика в целях ускорения процесса взаимодействия.

**Критерии приемки:**
При нажатии по кнопке/иконке "Чат" из личного кабинета происходит переход на страницу переписки.
Отображаются все сообщения переписки, сортированные по дате отправке, а также поле для ввода нового сообщения.
После ввода текста в поле и отправки сообщения необходимо отправить ajax запрос на сервер, добавить запись в сущность и вернуть обновленные данные. После чего сразу отображается последнее отправленное автором сообщение .

**Comment by Alnazhm** [comment]
Сделано
