### ISSUE TITLE
Добавление ученика в список учеников репетитора

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#57]
**Конечный результат:**
Необходимо дать возможность репетитору добавить потенциального ученика в свои ученики, если он подходит критериям репетитора. А также добавлять данного ученика в созданное в расписании занятие.

**План решения:**
- в кабинете репетитора реализовать вкладку-шаблон "Мои ученики".  Во вкладку "Мои ученики" добавляется карточка ученика.
- в приложении "Расписание" в события добавляются только те ученики, что добавлены в список учеников репетитора.
То есть после отклика и договорённости с учеником о занятии репетитор может создавать занятие в расписании и добавить в него этого ученика.
Необходимо предотвратить добавление одного ученика более одного раза в событие в расписании, а также в ученики.

**Мотивация:**
После получения отклика репетитор имеет возможность добавить потенциального ученика к себе в ученики и, после договорённости с учеником о занятии, репетитор может создавать занятие в расписании и добавить в него этого ученика.

**Критерии приемки:**
После отправки учеником отклика репетитор во вкладе-шаблоне "Отклики на меня" видит в карточке ученика кнопку "В ученики", всплывает модалка о подтверждении добавления, после подтверждения модалка закрывается и в правом нижнем углу всплывает уведомление о том, что ученик успешно добавлен в ученики репетитора, после чего исчезает через несколько секунд.

**Comment by Alnazhm** [comment]
Сделано
