### ISSUE TITLE
Исправление бага в навбаре

### ISSUE THREAD

**Issue by Rashid-ad-din** [ladukwek/ESDP-AP7-ATTRACTOR#58]
**Шаги воспроизведения:**
1. Открыть приложение расписания у репетитора.
2. Открыть кабинет репетитора.

**Наблюдаемые поведение:**
1. Навбар теряет стили, а sidebar слева оказывается слоем выше него и закрывает лого, а также приобретает общий стиль проекта.
2. Внутренний навбар репетитора при увеличении масштаба не адаптивен.

Ожидаемые поведение:
1. Навбар перекрывает сайдбар.
2. При увеличении масштаба внутренний навбар репетитора адаптируется под масштаб.

Причины:
1. Не соответствует стилю.
2.  При увеличении масштаба невозможно ориентироваться в контенте, внутренний навбар компануется в бургер, при этом тяжело определить его местоположение и он узкий и похож на знак минус.

Варианты решения:
2. Ко внутреннему навбару применить горизонтальный скролл.

**Comment by Alnazhm** [comment]
Сделано
