### ISSUE TITLE
Создание отзывов к репетиторам

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#62]
### Конечный результат:
Реализовать функционал создания отзывов учеников на репетиторов.
Если ученик находится в списке учеников репетитора, то он может оставить отзыв.
В кабинете ученика создать вкладку "Мои преподаватели"
Если ученик занимается у преподавателя, то этот преподаватель отражается во вкладке "Мои преподаватели"
в виде карточки с кнопкой "Оставит отзыв"
Создать вкладку "Отзывы" в кабинете ученика
На ней будут отображаться отзывы ученика на преподавателя в виде карточки с текстом отзыва и оценкой.

<img width="760" alt="Снимок экрана 2023-01-22 в 22 13 07" src="https://user-images.githubusercontent.com/113998948/213926505-b75c331a-222c-405c-b417-157060dda445.png">

### План решения:

1. Создать вкладку "Мои преподаватели"
2. Создать шаблон для этой вкладки, описать маршрутизацию на неё и представление, выводящее список преподавателей.
3. Поместить кнопку  "Создать отзыв" в карточку с преподавателем
4. Создать страницу для создания отзыва где будет загружаться форма для создания отзыва.
5. Создать вкладку "Мои отзывы"
6. Создать модель Отзыв, создать форму создания отзыва. 
7. На странице создания отзыва вывести поля формы а также две кнопки: "Оставить отзыв" и "Назад"
8. Создать шаблон для этой вкладки, описать маршрутизацию на неё и представление, выводящее список отзывов студента на преподавателей. 
9. 
![Otzyv](https://user-images.githubusercontent.com/113420698/214274359-b645d095-77a3-406e-af92-40fd520b82a9.png)

### Мотивация:
Функционал необходим для оценки Репетитиров и получения обратной связи от Учеников. Таким образом Ученики могут по рейтингу или отзывам быстро и легко найти лучших Репетитров и оставлять отзывы, также Репетиторы  могут улучшать свои навыки преподавания.
### Критерии приемки:
Авторизуемся под учеником. При нажатии на вкладку "Мои преподаватели" открывается список его преподавателей. Каждый преподаватель в отдельной карточке. При нажатии на кнопку "Создать отзыв" открывается страница с формой отзыва, где пользователь(ученик) заполняет поле "Текст отзыва" текстом отзыва и в выпадающем списке выбирает оценку от 1 до 5. При нажатии на кнопку "Оставить отзыв" пользователь попадает во вкладку "Мои отзывы" и наблюдает  карточку с отзывом на преподавателя. 
Заполняем форму и нажимаем "Оставить отзыв" 
При нажатии кнопки "Назад" возвращаемся на вкладку "Мои учителя"
### Планируемое время выполнения:
15 часов

**Comment by asmossunov** [comment]
Затрачено 22 часа

**Comment by TanitaDev** [comment]
#### Планируемое время - 15 часов

**Навбар**
созданы вкладки: 
- мои преподаватели
- отзывы


**Сверстала страницы:**
- мои преподаватели со списком всех преподавателей студента и ссылкой на страницу создания отзыва.
- мои отызвы со списком моих отзывов, где отображается фото преподавателя, имя, текст отзыва и рейтинг. 
- страница для оставления отзыва с формой для текста отзыва и звездным рейтингом.

Создала модель для отзывов.

**Создала views:**
- вывод преподавателей студента
- вывод всех отзывов
- написание самого отзыва

Создала отображение рейтинга radio button в виде звездочек

Зарегистрировала модель в админке

#### Затраченное время - 22 часа
