### ISSUE TITLE
Регистрация репетитора

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#7]
### Конечный результат:
Чтоб когда будем выбирать из выпадающего списка выбираем Репетитора и должно открыться окно регистрации репетитора

### Мотивация:
Для того , чтобы пользователь мог произвести регистрацию как репетитор и он отличался по своим правам и возможностям от других типов пользователей его необходимо зарегистрировать с типом "tutor"

### План решения:
Создать модель Tutor в отдельном файле.
Заменить в классе формы авторизации LoginForm значение label "login" на "Email"
В шаблоне создать ссылку на создание аккаунта Tutor (регистрация).
Пользователь с типом Tutor(репетитор) создаётся также как обычный пользователь. 
Используется одно представление для всех типов пользователей.
Далее в зависимости от типа созданного пользователя происходит переадресация на представление для 
заполнения доп. модуля характерного именно для этого типа пользователя. 

  Сначала регистрируется пользователь, далее после переадресации создаётся его модуль 
  (таблица с   дополнительными полями)
  Необходимо привязать пользователя к моделю:
  Создаем поле user связанное через OneToOneField с пользователем.
  Далее описываются поля: place_of_study - место учебы и  working_place - место работы.
  
  Создать шаблоны с формой регистрации доп. модуля.
  Название шаблона должно отражать суть создаваемого модуля
  
  Создать маршрутизацию в urls. 
  
  Создать форму StudyCenterCreationForm  или с другим подходящим названием отражающим суть модуля, в файле forms.py:
  
### Критерий приёмки:
  
  На главной странице нажимаем кнопку регистрация.
  Выпадает список, в котором выбираем тип пользователя для регистрации
  После этого закружается форма для регистрации пользователя. После нажатия кнопки "зарегистрироваться" открывается дополнительная форма - для регистрации доп. модуля с двумя полями репетитора. После этого необходимо проверить в базе данных созданные записи. Должен создаваться пользователь в таблице account и с дополнительном модуле tutor - таблица
  
### Планируемое время:
3 часа

**Comment by Rashid-ad-din** [comment]
Задача завершена.
Затраченное время - 1 час 50 минут.
