### ISSUE TITLE
Реализовать функционал оплаты

### ISSUE THREAD

**Issue by nurilaassyk** [ladukwek/ESDP-AP7-ATTRACTOR#70]
## Конечный результат:
* Реализовать функционал оплаты 

## План решения:
* Выбрать подходящий API для подключения оплаты
* Интегрировать оплату в проект

## Мотивация:
* Нужна для того, чтобы клиенты системы могли проводить оплату за полученную услугу

## Критерии приемки:
* После того, как ученик и учитель договорились на проведение занятия, показать кнопку оплатить в личном кабинете
* При нажатии на кнопку оплатить, выходит форма оплаты

## Планируемое время выполнения:
* 7 часов

**Comment by asmossunov** [comment]
Реализовал за 8 часов
