### ISSUE TITLE
Реализация фильтра при поиске объявлений

### ISSUE THREAD

**Issue by nurilaassyk** [ladukwek/ESDP-AP7-ATTRACTOR#71]
## Конечный результат:
* Реализовать фильтр при поиске объявлений

## План решения:
* Написать запросы в базу на выборку таблиц подходящих фильтрации
* Привязать функционал фильтра к страницам board_tutor и board_student

## Мотивация:
* Нужна для того, чтобы пользователь смог найти объявления соответствующие его предпочтениям

## Критерии приемки:
* При выборе того или иного фильтра видим результат совпадающий с фильтром

## Планируемое время выполнения:
* 5 часов

## Фактическое затраченное время выполнения:
* 10 часов

**Comment by Rashid-ad-din** [comment]
Задача принята

**Comment by Alnazhm** [comment]
Фактическое затраченное время выполнения 10 часов
