### ISSUE TITLE
Модульное тестирование 

### ISSUE THREAD

**Issue by nurilaassyk** [ladukwek/ESDP-AP7-ATTRACTOR#72]
## Конечный результат:
Написан тест на регистрацию и вход пользователя

## План решения:
* Добавить файл tests.py
* Написать тесты для проверки регистрации и входа

## Мотивация:
* Нужна для того, чтобы проверять работоспособность функционала регистрации и входа

## Критерии приемки:
* Запустить тесты
* Увидим что создается пользователь в базе
* Увидим успешный вход в систему через тестового пользователя

## Планируемое время выполнения:
* 28 час

**Comment by asmossunov** [comment]
Реализовал за 56 часов

**Comment by Rashid-ad-din** [comment]
Работа принята.
