### ISSUE TITLE
Детальная страница репетитора и студента

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#75]
### Конечный результат:
- Репетитор:
  Выводится подробная страница репетитора, где отображены данные репетитора: ФИО, телефон, аватар, предметы, рейтинг, отзывы и прогресс бар
- Студент:
 выводится подробная информация о студенте, где отображены: ФИО, телефон, аватар, желаемые предметы студента

### Мотивация:
Детальные страницы нужны для просмотра более подробной информации о пользователе.

### План решения:
- сверстать детальные страницы
- создать необходимые view
- прописать urls
- вывести информацию о пользователе в шаблонах

### Критерии приёма:
- детальные страницы должны быть аккуратные
- показывать подробную информацию о репетиторе и ученике

**Comment by asmossunov** [comment]
Затратил 9 часов
