### ISSUE TITLE
Инструкция по запуску проекта для заказчика 

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#76]
### Конечный результат:
Описение действий для запуска проекта локально для заказчиков.

### Мотивация:
Инструкция к запуску проекта необходима для того, что бы заказчик мог у себя на компьютере локально запустить проект для просмотра страниц и функционала.

### План решения:
Описать как установить нужные библиотеки, установить виртуальное окружение, сделать миграции, загрузить фикстуры и запустить проект на локальном порту 8000

### Критерии приёма:
- Инструкиция должна быть на русском языке
- Описение должно быть последовательным
- Заказчику должно быть понятно как читать инструцию

**Comment by asmossunov** [comment]
Подготовила за 1 час
