### ISSUE TITLE
Исправление багов в проекте

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#79]
### Конечный результат:
Исправленны баги:
- переключение по вкладкам навбара личных кабинетов
- доработка фильтра 
- изменение положения часов в личном кабинете
- исправлен баг повторяющихся учеников/репетиторов
- баг отображения опыта работы репетитора

### Мотивация:
Исправления багов нужно для корректной работы функционала проекта, для заполнения пробелов при написании нового функционала.

### План решения:
- Проверить пошагово весь имеющийся функционал проекта и выявить багги
- Исправить выявленные

### Критерии приёма:
- Фильтр должен коректно работать - искать репетиторов на выбранным критериям
- Часы переместить в левый сайтбар личного кабинета
- При переключении навраба неактивные вкладки окрашивабтся в серый цвет
- Ученики и репетиторы не повторяются при отображении на досках объявлений
- Скорректированны стилистические несоответствия
- На подробной странице репетитора исправлено отображение опыта работы -  отображаются значение репетитора, а не аккаунта.

**Comment by Rashid-ad-din** [comment]
Планируемое время 10 часов.
Затраченное время 16 чаов.

**Comment by Alnazhm** [comment]
Выполнено
