### ISSUE TITLE
Расписение в кабинетах пользователя

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#81]
### Конечный результат:
Пользователь видит свое расписание на гланой странице
У родителя выводится расписание всех его детей
В расписании есть вкладки: номер, занятие, начало, окончание, ученик, форма обучения
Со стороны ученика, ученик должен видеть кто его преподователь, а репетитор кто его ученик.

### Мотивация:
Расписание необходимо для ориентации во времени, чтобы пользователь видел когда с кем и во сколько какой урок. 

### План решения:
- Сверстать таблицу с расписанием
- Написать необходимую view для вывода расписания

### Критерии приёма:
- Расписание отображается в видео таблицы
- Выводится информация о предмете, ученике, репетиторе, времени и форме обучения

**Comment by asmossunov** [comment]
Выполнил за 6 часов
