### ISSUE TITLE
Внедрение vue js в проект

### ISSUE THREAD

**Issue by TanitaDev** [ladukwek/ESDP-AP7-ATTRACTOR#85]
### Конечный результат:
Использоваав vue js, появляется возможность сделать связные списки областей, городов, районов, улиц.
При нажатии на определенный район отображаются связанные с ним города и так далее по цепочке.

### Мотивация:
Связные списки нужны для того, чтобы пользователю было удобно заполнить анкету. Это упростит и ускорит поиск адреса при заполнении.

### План решения:
- Связать Django и Vue js
- Сделать возможность использовать компонент vue в шаблонах Django
- Описать компомнент вью для связных списков

### Критерии приема:
- При определенном выборе, выходит следующий список привязанный к выбранному ранее элементу
- Vue js привязан к Django не как отдельный фронт, а как дополнение уже к имеющимся шаблонам

**Comment by Alnazhm** [comment]
Выполнено
