### ISSUE TITLE
Регистрация родителя

### ISSUE THREAD

**Issue by Alnazhm** [ladukwek/ESDP-AP7-ATTRACTOR#9]
### Конечный результат:  
На сайте должен выводиться форма регистрации Родителя

### Мотивация:
Чтоб тип пользователя Родитель работал и имел возможности регистрироваться 

### План решения:
В шаблоне создать ссылку на создание аккаунта Parent (регистрация).
  Создать шаблоны с формой регистрации 
  Настроить маршрутизацию. 
  Создать представление для создания пользователя Parent. 
  Проверить работоспособность. Сначала регистрируется пользователь, 
  далее после переадресации создаётся его модуль (таблица с дополнительными полями)
  Создать шаблоны с формой регистрации доп. модулей  
  
###   Планируемое время: 
5:00

**Comment by asmossunov** [comment]
Родитель регистрируется. Функционал реализован. После регистрации попадает в личный кабинет где может регистрировать детей-учеников.
Затрачено 3 часа.
